import Lean.Data.Json

/-! # Markdown generation from JSON Schema

Reads the JSON Schema (generated by DocGen.Schema) and transforms it
into a human-readable markdown reference. This module does NOT import
Qed.Types — it only knows about JSON Schema structure.

The pipeline: Lean types → JSON Schema → Markdown
-/

namespace DocGen.Markdown

open Lean

private def getString (json : Json) (key : String) : String :=
  match json.getObjValAs? String key with
  | .ok value => value
  | .error _ => ""

private def getArray (json : Json) (key : String) : Array Json :=
  match json.getObjValAs? (Array Json) key with
  | .ok value => value
  | .error _ => #[]

private def getObject (json : Json) (key : String) : Json :=
  match json.getObjVal? key with
  | .ok value => value
  | .error _ => Json.null

/-- Format a default value from a JSON property descriptor. -/
private def formatDefault (property : Json) : String :=
  match property.getObjVal? "default" with
  | .ok (Json.str value) => s!"`\"{value}\"`"
  | .ok (Json.num value) => s!"{value}"
  | _ => "—"

/-- Check if a field name appears in a JSON Schema required array. -/
private def isRequired (fieldName : String) (requiredFields : Array Json) : Bool :=
  requiredFields.any (· == Json.str fieldName)

/-- Get the display type string for a JSON Schema property. -/
private def formatType (property : Json) : String :=
  match property.getObjVal? "const" with
  | .ok (Json.str value) => s!"`\"{value}\"`"
  | _ => getString property "type"

/-- Configuration for rendering a properties table. -/
structure TableConfig where
  /-- Whether to include a Description column. -/
  includeDescription : Bool
  /-- Override type names for specific fields (e.g., "worker" → "[Worker](#worker)"). -/
  typeOverrides : List (String × String) := []

/-- Pad a string with trailing spaces to reach the given width. -/
private def padRight (s : String) (width : Nat) : String :=
  let padding := width - s.length
  s ++ String.ofList (List.replicate padding ' ')

/-- Render a padded markdown table from rows of cell values.
    Prettier requires columns to be padded to equal width. -/
private def renderPaddedTable (headers : List String) (rows : List (List String)) : String :=
  let allRows := headers :: rows
  let columnCount := headers.length
  let columnWidths := List.range columnCount |>.map fun columnIndex =>
    allRows.foldl (init := 0) fun maxWidth row =>
      match row[columnIndex]? with
      | some cell => Nat.max maxWidth cell.length
      | none => maxWidth
  let formatRow (cells : List String) : String :=
    let paddedCells := (cells.zip (List.range cells.length)).map fun (cell, index) =>
      match columnWidths[index]? with
      | some width => padRight cell width
      | none => cell
    "| " ++ " | ".intercalate paddedCells ++ " |"
  let separatorCells := columnWidths.map fun width =>
    String.ofList (List.replicate width '-')
  let separator := "| " ++ " | ".intercalate separatorCells ++ " |"
  let headerLine := formatRow headers
  let rowLines := rows.map formatRow
  s!"{headerLine}\n{separator}\n{"\n".intercalate rowLines}"

/-- Render a JSON Schema properties object as a markdown table.

Extracts the shared pattern: iterate over key-value pairs in a properties
object, format each as a table row with field name, type, required status,
and default value. Columns are padded for prettier compatibility. -/
private def renderPropertiesTable (schema : Json) (config : TableConfig) : String :=
  let requiredFields := getArray schema "required"
  let properties := getObject schema "properties"
  let headers := if config.includeDescription
    then ["Field", "Type", "Required", "Default", "Description"]
    else ["Field", "Type", "Required", "Default"]
  let rows : List (List String) := match properties with
    | Json.obj keyValues =>
      keyValues.toArray.toList.map fun (fieldName, property) =>
        let fieldType := match config.typeOverrides.find? (fun pair => pair.1 == fieldName) with
          | some (_, override) => override
          | none => formatType property
        let required := if isRequired fieldName requiredFields then "yes" else "no"
        let defaultValue := formatDefault property
        if config.includeDescription then
          let description := getString property "description"
          [s!"`{fieldName}`", fieldType, required, defaultValue, description]
        else
          [s!"`{fieldName}`", fieldType, required, defaultValue]
    | _ => []
  renderPaddedTable headers rows

/-- Render a oneOf variant as a markdown subsection. -/
private def renderVerifyVariant (variant : Json) : String :=
  let properties := getObject variant "properties"
  let typeProperty := getObject properties "type"
  let typeName := getString typeProperty "const"
  let description := getString variant "description"
  let table := renderPropertiesTable variant { includeDescription := true }
  s!"### `{typeName}`\n\n{description}\n\n{table}"

/-- Generate the full markdown reference from a JSON Schema string. -/
def generate (schemaString : String) : Except String String := do
  let schema ← Json.parse schemaString
  let properties := getObject schema "properties"
  let criteria := getObject properties "criteria"
  let items := getObject criteria "items"
  let itemProperties := getObject items "properties"
  let verify := getObject itemProperties "verify"
  let scheduleProperty := getObject itemProperties "schedule"
  let variants := getArray verify "oneOf"

  -- Top-level structure table
  let topLevelTable := renderPropertiesTable schema {
    includeDescription := true
    typeOverrides := [("worker", "[Worker](#worker)"), ("criteria", "[Criterion](#criterion)[]")]
  }

  -- Worker table
  let workerSchema := getObject properties "worker"
  let workerTable := renderPropertiesTable workerSchema { includeDescription := true }

  -- Criterion table
  let criterionTable := renderPropertiesTable items {
    includeDescription := true
    typeOverrides := [("verify", "[VerifyType](#verification-types)"), ("schedule", "[Schedule](#schedule)")]
  }

  -- Verify type sections
  let verifySections := variants.map renderVerifyVariant

  -- Schedule table
  let scheduleEnumValues := getArray scheduleProperty "enum"
  let scheduleData : List (List String) := scheduleEnumValues.toList.filterMap fun value =>
    match value with
    | Json.str s => match s with
      | "always" => some ["`always`", "Every run — CI, pre-push, explicit", "`command`, `property`, `proof`"]
      | "heavy" => some ["`heavy`", "Included with `--extended`, excluded by default in CI", "`agent`"]
      | "manual" => some ["`manual`", "Only via explicit `qed run` or `qed verify` (no flags)", "`human`"]
      | other => some [s!"`{other}`", "", ""]
    | _ => none
  let scheduleTable := renderPaddedTable ["Value", "Description", "Default for"] scheduleData

  Except.ok s!"# Spec Format Reference

> **Auto-generated** from the Lean types in [`Qed/Types.lean`](../Qed/Types.lean) via JSON Schema.
> Do not edit — run `devbox run docs` to regenerate.

Specs are written in JSON (`.spec.json`) or TOML (`.spec.toml`). Both formats parse into the same types. Use JSON for simple specs, TOML when you need multi-line strings (agent review prompts, human instructions).

Schema: [`spec.schema.json`](spec.schema.json) — add `\"$schema\": \"docs/spec.schema.json\"` (JSON) or `#:schema docs/spec.schema.json` (TOML) for editor autocomplete.

## Structure

{topLevelTable}

## Execution modes

A spec runs in one of two modes, determined by whether `worker` is present:

- **Worker loop** (`worker` present) — run the worker, verify criteria, feed failures back, repeat until all pass or the loop terminates (stuck / max iterations).
- **Verify** (`worker` absent) — run each criterion once and report results. Requires at least one criterion. Used for CI checks and standalone verification.

`maxIterations` and `stuckThreshold` only apply in worker loop mode.

## Worker

Optional. If present, qed runs in worker loop mode. The worker is the command that attempts to satisfy the criteria — an AI agent, a build command, a script, anything with a shell interface.

{workerTable}

## Criterion

Each criterion has a description, a verification strategy, and a schedule.

{criterionTable}

## Verification types

Five verification strategies, from lightweight to mathematical:

{"\n\n".intercalate verifySections.toList}

## Schedule

Controls when a criterion runs. The runner filters by this field based on the execution context (`--auto`, `--extended`, `--full`, or no flag).

{scheduleTable}

See [architecture.md](architecture.md) for the full state machine diagram and transition rules."

end DocGen.Markdown
